### ISSUE TITLE
Create spec file and tests for the 'Password' input field.

### ISSUE THREAD

**Issue by markodelgadillo** [markodelgadillo/DisneyMovieInsiders#17]
# Tasks: #

- [x] Create the spec file for the password input field.

## Create tests for the following: ##
- [x] Verify the input field exists/is displayed.
- [x] Verify the input field error UI is displayed.
---
- Verify the input field error messages are displayed:
> - [x] "Please enter a password."
> - [x] "The password is too short."
> - [x] "The password is too easily guessed."
---
- [x] Verify the password minimum requirements are displayed.
---
- Verify the password strength value:
> - [x] "Weak"
> - [x] "Ok"
> - [x] "Strong"
---
- [x] Verify the "Show Password" checkbox.
