### ISSUE TITLE
Create the first test file for Cypress automation.

### ISSUE THREAD

**Issue by markodelgadillo** [markodelgadillo/DisneyMovieInsiders#3]
### Creating the first set of tests for the Disney Movie Insiders web page within the Cypress.io automation app.

**Tasks**

1. Create the first file for tests.
2. Write the first tests:

**Tests**
- [x] Verify the 'Sign Up' button is visible
- [x] Verify the 'Sign In' button is visible
- [x] Verify the 'Disney.com' link is visible
- [x] Verify the 'Get The App' link is visible
- [x] Verify the 'Disney.com' link is visible
- [x] Verify the 'Link Accounts' link is visible
- [x] Verify the 'Upload Tickets' link is visible
- [x] Verify the 'Enter Code' button is visible
